MODULE = pcm_mse
DIRC   = ../pcm_common

FILES  = Main.o $(DIRC)/Common.o
LIBS   = -lconvert -lfft -lmathex -lriffio -lcmdline -lprofiler -lm

CMP    = $(CPP)
EXT    = cpp

include ../../projects/makedef.mk
include ../maketst.mk
